- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-west-1
    ami: ami-06e46074ae430fba6 
    instance_type: t2.micro
    keypair: my-virginia
    security_group: sg-00afa7e9f6f579214
    subnet_id: subnet-0cd6fc87f6c21616a
    tag_Name: my_ec2_instance

  tasks:
  - name: Launching an EC2 instance
    ec2:
      region: "{{ region }}"
      image: "{{ ami }}"
      instance_type: "{{ instance_type }}"
      key_name: "{{ keypair }}"
      group_id: "{{ security_group }}"
      subnet_id: "{{ subnet_id }}"
      assign_public_ip: true
      wait: true
      count: 1
      instance_tags:
        Name: "{{ tag_Name }}"
    register: ec2

  - name: Add the new EC2 instance to host group
    add_host:
      name: "{{ item.public_ip }}"
      groups: launched
    with_items: "{{ ec2.instances }}"

